apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-streaming
  namespace: nats-io
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nats-streaming
  name: nats-streaming
  namespace: nats-io
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nats-streaming
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
      - args:
        - -cid
        - nats-streaming
        - -m
        - "8222"
        - -ns
        - http://nats.nats-io:4222
        - -mc
        - "100"
        - -msu
        - "1000"
        - -mm
        - "1000000"
        - -mb
        - 900mb
        - -ma
        - "0"
        - -hbi
        - 30s
        - -hbt
        - 10s
        - -hbf
        - "330"
        - --store
        - file
        - --dir
        - /nats/nss
        - --file_compact_enabled
        - --file_compact_frag
        - "50"
        - --file_compact_interval
        - "300"
        - --file_compact_min_size
        - "1048576"
        - --file_buffer_size
        - "2097152"
        - --file_crc
        - --file_crc_poly
        - "3988292384"
        - --file_sync
        - --file_slice_max_msgs
        - "0"
        - --file_slice_max_bytes
        - "67108931"
        - --file_slice_max_age
        - "0"
        - --file_fds_limit
        - "0"
        - --file_parallel_recovery
        - "1"
        - --ft_group
        - ft-nats-streaming
        image: nats-streaming:0.10.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8222
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nats-streaming
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8222
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /nats/nss
          name: data
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nats-streaming