apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nats
  namespace: nats-io
  labels:
    component: nats
spec:
  serviceName: nats
  replicas: 3
  selector:
    matchLabels:
      component: nats
  template:
    metadata:
      labels:
        component: nats
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "7777"
    spec:
      volumes:
      # - name: tls-volume
        # secret:
          # secretName: tls-nats-server
      - name: config-volume
        configMap:
          name: nats-config
      containers:
      - name: nats
        image: nats:1.1.0
        args: [ "--config", "/etc/nats/config/nats.conf"]
        volumeMounts:
          # - name: tls-volume
          #   mountPath: /etc/nats/tls
          - name: config-volume
            mountPath: /etc/nats/config
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 250Mi
      - name: prometheus-nats-exporter
        image: mwrona/prometheus-nats-exporter:0.1.0
        imagePullPolicy: IfNotPresent
        args: ["-varz", "-connz", "-routez", "-subz", "http://localhost:8222"]
        ports:
        - name: http
          containerPort: 7777
        resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        - name: platform-docker-registry
